# This file is generated by scripts/update.py. Do not edit manually.
class Deepseek < Formula
  desc "Stateless DeepSeek subagent CLI"
  homepage "https://github.com/model-clis/deepseek"
  url "https://github.com/model-clis/deepseek/releases/download/v2026.726.0/deepseek-macos-aarch64"
  version "2026.726.0"
  sha256 "8de4b4e912373dea1a15f8bb03bfedff47bdf7ebb8d33f620ffe5e8c8b541e42"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "deepseek-macos-aarch64" => "deepseek"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deepseek --version")
  end
end
