# This file is generated by scripts/update.py. Do not edit manually.
class Deepseek < Formula
  desc "Stateless DeepSeek subagent CLI"
  homepage "https://github.com/model-clis/deepseek"
  url "https://github.com/model-clis/deepseek/releases/download/v2026.716.0/deepseek-macos-aarch64"
  version "2026.716.0"
  sha256 "971420d8ffcc9732c1909f006b26e233b0919bc33b5691d9c2fffccffffa0e44"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "deepseek-macos-aarch64" => "deepseek"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deepseek --version")
  end
end
