# This file is generated by scripts/update.py. Do not edit manually.
class Deepseek < Formula
  desc "Stateless DeepSeek subagent CLI"
  homepage "https://github.com/model-clis/deepseek"
  url "https://github.com/model-clis/deepseek/releases/download/v2026.723.0/deepseek-macos-aarch64"
  version "2026.723.0"
  sha256 "d69410fa0320331ad89f3f2d3a9d8977a312aaced8588b4da47d7ca29cda2fe0"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "deepseek-macos-aarch64" => "deepseek"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deepseek --version")
  end
end
