# This file is generated by scripts/update.py. Do not edit manually.
class Jev < Formula
  desc "Typed judgment CLI for the Jev model"
  homepage "https://github.com/model-clis/jev"
  url "https://github.com/model-clis/jev/releases/download/v2026.919.0/jev-macos-aarch64"
  version "2026.919.0"
  sha256 "b407275845732cf5fa791437ba5b0185fd6dcb411bec16f3d733c7b02f991c42"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "jev-macos-aarch64" => "jev"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jev --version")
  end
end
