#!/usr/bin/env python3
import json
import os
import re
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")


def fetch(url: str) -> bytes:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "model-clis-package-updater",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token := os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {token}"
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
        return response.read()


def checksum(assets: dict[str, str], name: str) -> str:
    checksum_name = f"{name}.sha256"
    if checksum_name not in assets:
        raise RuntimeError(f"release is missing {checksum_name}")
    value = fetch(assets[checksum_name]).decode("utf-8").split()[0].lower()
    if not SHA256.fullmatch(value):
        raise RuntimeError(f"invalid SHA-256 in {checksum_name}")
    return value


def ruby_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def update(name: str, package: dict[str, object]) -> None:
    repository = str(package["repository"])
    release = json.loads(fetch(f"https://api.github.com/repos/{repository}/releases/latest"))
    tag = release["tag_name"]
    if not re.fullmatch(r"v\d{4}\.\d+\.\d+", tag):
        raise RuntimeError(f"unsupported release tag for {name}: {tag}")
    version = tag[1:]
    assets = {asset["name"]: asset["browser_download_url"] for asset in release["assets"]}
    configured_assets = package["assets"]
    homebrew_asset = str(configured_assets["homebrew"])
    scoop_asset = str(configured_assets["scoop"])
    for asset in (homebrew_asset, scoop_asset):
        if asset not in assets:
            raise RuntimeError(f"release is missing {asset}")

    class_name = "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", name))
    formula = f'''# This file is generated by scripts/update.py. Do not edit manually.
class {class_name} < Formula
  desc "{ruby_string(str(package['description']))}"
  homepage "{ruby_string(str(package['homepage']))}"
  url "{assets[homebrew_asset]}"
  version "{version}"
  sha256 "{checksum(assets, homebrew_asset)}"
  license "{ruby_string(str(package['license']))}"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "{homebrew_asset}" => "{name}"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/{name} --version")
  end
end
'''
    formula_path = ROOT / "Formula" / f"{name}.rb"
    formula_path.parent.mkdir(parents=True, exist_ok=True)
    formula_path.write_text(formula, encoding="utf-8", newline="\n")

    scoop = {
        "version": version,
        "description": package["description"],
        "homepage": package["homepage"],
        "license": package["license"],
        "architecture": {
            "64bit": {
                "url": assets[scoop_asset],
                "hash": checksum(assets, scoop_asset),
            }
        },
        "bin": [[scoop_asset, name]],
        "checkver": {"github": package["homepage"]},
        "autoupdate": {
            "architecture": {
                "64bit": {
                    "url": f"https://github.com/{repository}/releases/download/v$version/{scoop_asset}",
                    "hash": {"url": "$url.sha256"},
                }
            }
        },
    }
    bucket_path = ROOT / "bucket" / f"{name}.json"
    bucket_path.parent.mkdir(parents=True, exist_ok=True)
    bucket_path.write_text(json.dumps(scoop, indent=2) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    packages = json.loads((ROOT / "packages.json").read_text(encoding="utf-8"))
    for name, package in sorted(packages.items()):
        update(name, package)


if __name__ == "__main__":
    main()
