#!/usr/bin/env python3
import json
import os
import re
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")


def fetch(url: str) -> bytes:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "model-clis-package-updater",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token := os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {token}"
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
        return response.read()


def checksum(assets: dict[str, str], name: str) -> str:
    checksum_name = f"{name}.sha256"
    if checksum_name not in assets:
        raise RuntimeError(f"release is missing {checksum_name}")
    value = fetch(assets[checksum_name]).decode("utf-8").split()[0].lower()
    if not SHA256.fullmatch(value):
        raise RuntimeError(f"invalid SHA-256 in {checksum_name}")
    return value


def ruby_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def resolve_release(name: str, package: dict[str, object]) -> tuple[dict, str]:
    """Return (release, version) for a package.

    Default scheme: the repository's latest release, tagged `vYYYY.M.P`.
    Packages that set `tag_prefix` (e.g. upstream monorepos tagging
    `@scope/pkg@1.2.3`) instead pick the newest non-draft, non-prerelease
    release whose tag starts with the prefix, and the version is the
    remainder of the tag.
    """
    repository = str(package["repository"])
    tag_prefix = package.get("tag_prefix")
    if tag_prefix:
        releases = json.loads(
            fetch(f"https://api.github.com/repos/{repository}/releases?per_page=100")
        )
        for release in releases:
            if release.get("draft") or release.get("prerelease"):
                continue
            tag = str(release["tag_name"])
            if not tag.startswith(str(tag_prefix)):
                continue
            version = tag[len(str(tag_prefix)):]
            if not re.fullmatch(r"\d+(\.\d+)+", version):
                raise RuntimeError(f"unsupported release tag for {name}: {tag}")
            return release, version
        raise RuntimeError(f"no release matching tag prefix {tag_prefix} for {name}")
    release = json.loads(fetch(f"https://api.github.com/repos/{repository}/releases/latest"))
    tag = str(release["tag_name"])
    if not re.fullmatch(r"v\d{4}\.\d+\.\d+", tag):
        raise RuntimeError(f"unsupported release tag for {name}: {tag}")
    return release, tag[1:]


def write_formula(name: str, package: dict[str, object], version: str,
                  assets: dict[str, str], homebrew_asset: str) -> None:
    class_name = "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", name))
    formula = f'''# This file is generated by scripts/update.py. Do not edit manually.
class {class_name} < Formula
  desc "{ruby_string(str(package['description']))}"
  homepage "{ruby_string(str(package['homepage']))}"
  url "{assets[homebrew_asset]}"
  version "{version}"
  sha256 "{checksum(assets, homebrew_asset)}"
  license "{ruby_string(str(package['license']))}"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "{homebrew_asset}" => "{name}"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/{name} --version")
  end
end
'''
    formula_path = ROOT / "Formula" / f"{name}.rb"
    formula_path.parent.mkdir(parents=True, exist_ok=True)
    formula_path.write_text(formula, encoding="utf-8", newline="\n")


def write_scoop_manifest(name: str, package: dict[str, object], version: str,
                         assets: dict[str, str], scoop_assets: dict[str, str]) -> None:
    repository = str(package["repository"])
    tag_prefix = str(package.get("tag_prefix") or "v")
    # File to shim inside the (possibly archived) asset. Defaults to the
    # x64 asset name itself, i.e. a bare executable; set `scoop_bin_source`
    # when the asset is an archive wrapping the binary.
    bin_source = str(package.get("scoop_bin_source") or scoop_assets["64bit"])
    bin_name = str(package.get("scoop_bin_name") or name)
    scoop = {
        "version": version,
        "description": package["description"],
        "homepage": package["homepage"],
        "license": package["license"],
        "architecture": {
            arch: {
                "url": assets[asset],
                "hash": checksum(assets, asset),
            }
            for arch, asset in scoop_assets.items()
        },
        "bin": [[bin_source, bin_name]],
        "checkver": package.get("checkver") or {"github": package["homepage"]},
        "autoupdate": {
            "architecture": {
                arch: {
                    "url": f"https://github.com/{repository}/releases/download/{tag_prefix}$version/{asset}",
                    "hash": {"url": "$url.sha256"},
                }
                for arch, asset in scoop_assets.items()
            }
        },
    }
    bucket_path = ROOT / "bucket" / f"{name}.json"
    bucket_path.parent.mkdir(parents=True, exist_ok=True)
    bucket_path.write_text(json.dumps(scoop, indent=2) + "\n", encoding="utf-8", newline="\n")


def update(name: str, package: dict[str, object]) -> None:
    release, version = resolve_release(name, package)
    assets = {asset["name"]: asset["browser_download_url"] for asset in release["assets"]}
    configured_assets = package["assets"]

    # `assets.scoop` is either a single x64 asset name or a per-architecture
    # map ({"64bit": ..., "arm64": ...}). `assets.homebrew` is a single
    # arm64 macOS asset name; omit it to skip Formula generation.
    homebrew_asset = configured_assets.get("homebrew")
    scoop_assets = configured_assets.get("scoop")
    if isinstance(scoop_assets, str):
        scoop_assets = {"64bit": scoop_assets}
    required = [str(homebrew_asset)] if homebrew_asset else []
    required += [str(asset) for asset in (scoop_assets or {}).values()]
    for asset in required:
        if asset not in assets:
            raise RuntimeError(f"release is missing {asset}")

    if homebrew_asset:
        write_formula(name, package, version, assets, str(homebrew_asset))
    if scoop_assets:
        write_scoop_manifest(name, package, version, assets, scoop_assets)


def main() -> None:
    packages = json.loads((ROOT / "packages.json").read_text(encoding="utf-8"))
    for name, package in sorted(packages.items()):
        update(name, package)


if __name__ == "__main__":
    main()
